# Setup
title:        Flutter by Examples
tagline:      Learn Flutter by Examples.
baseurl:      ""
paginate:     1
locale:       "en"
baseurl: "/flutter-by-examples"
url: "https://sumeetmathpati.github.io"

# About/contact
author:
  name:       Sumeet Mathpati
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
kramdown:
  input: GFM
  entity_output: :as_input
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  dart-basics:
    output: true
    
# Default frontmatter
defaults:
  - scope:
      path: ""
      type: "dart-basics"
    values:
      layout: "default"
      section-name: "dart-basics"